.Dd June 21, 2020
.Os Unix
.Dt ID3V2 1 "User Commands"
.Sh NAME
.Nm aov-html2epub
.Nd Takes a list of HTML files and turns them into a v. 3 EPUB.
.Sh SYNOPSIS
.Nm
.Op
.Ar EPUB FILE
.Fl t Ar title
.Fl a Ar name
.Fl f Ar reversename
.Fl s Ar subject
.Fl p Ar creator          
.Fl p Ar publisher        
.Fl T Ar translator       
.Fl c Ar cover.img        
.Fl l Ar lang             
.Fl L Ar license
.Fl u Ar uuid
.Ar FILES
\&...
.Sh DESCRIPTION
.Nm
copies HTML files into a subdirectory, OPS, and generates files, correctly formatted:
.Bl -column
.It Ar mimetype
.It Ar container.xml
.It Ar content.opf
.It Ar toc.xhtml
.It toc.ncx
.It Ar titlepage.xhtml
.El
If you provide the titlepage in the build directory,
.Nm
will copy that instead of creating its own. Only the EPUB name, one or more
HTML files, and a book title are required to build an EPUB, all other options and
files are optional.
.Pp
HTML, CSS, TTF, WOFF and image files can be added.
.Xr file 1
is used to generate the MIME type and
.Xr zip 1
to generate the EPUB. If a UUID is not provided with the
.Fl u
option,
.Xr uuidgen 1
will be used to generate one. All HTML files specified on the command line
will be added as a part of the content, in the same order as on invocation. Only
.Sy generated
files are removed when the program completes.
.Sh OPTIONS
.Bl -tag
.It Fl t Ar title
Book title,
.Sy required
.It Fl a Ar name
Author name, "First Last"
.It Fl f Ar reverse name
Author name, "Last, First"
.It Fl s Ar subject
Subject(s)
.It Fl p Ar creator          
EPUB creator
.It Fl p Ar publisher        
Publishing house
.It Fl T Ar translator       
Translator
.It Fl c Ar cover.img        
Cover image
.It Fl l Ar lang             
Language (RFC 4646, default "en-US")
.It Fl L Ar license
Content licence, default "none"
.It Fl u Ar uuid
Universal Unique ID
.El
.Sh EXAMPLES
.Xr make 1
is an excellent tool for building and updating EPUBs with this script. 
.Sh SEE ALSO
.Xr zip 1 , Xr uuidgen 1 , Xr file 1 .
.Sh AUTHOR
.Nm
was originally by
.An Angel Ortega ,
which made me, 
.An somercet , realize EPUBs were actually simple.
The original and this heavily modified version are publicly available at
.Lk https://github.com/somercet/aov-html2epub Github .
"Released under the public domain. Use as you want, specially for evil."
